#!/usr/bin/env python3
"""Rebuild townad-demo.html from d.html.

The sample dashboard is the REAL d.html with exactly three stubs. Keeping this as a script
(rather than hand-editing the copy) is the point: the sample drifted from d.html twice
already, and a stale sample is worse than none — it shows prospects a product we don't ship.

Run after ANY change to d.html:   python3 scripts/build-townad-demo.py
"""
import re, sys, pathlib

SRC = pathlib.Path(__file__).resolve().parent.parent / "d.html"
OUT = SRC.parent / "townad-demo.html"

s = SRC.read_text(encoding="utf-8")

def sub_once(hay, old, new, what):
    n = hay.count(old)
    if n != 1:
        sys.exit(f"ABORT: expected exactly 1 occurrence of {what}, found {n}. d.html changed — fix this script.")
    return hay.replace(old, new, 1)

# 1. stub the DB lookup
s = sub_once(s,
    'const sb=supabase.createClient(SB_URL,SB_KEY);',
    '''/* ── SAMPLE DASHBOARD — generated by scripts/build-townad-demo.py, do not hand-edit ──
   The real d.html with three stubs: the DB lookup, the QR target, and the token. The QR
   generator, the printable-asset canvas, the island labelling and the promo preview are all
   the genuine code paths a paying partner gets. Sample data — not a real business. */
const _P=new URLSearchParams(location.search);
const _REGION={oahu:"Waikīkī",kauai:"Poʻipū",maui:"Kīhei"};
const _ISL=(_P.get("isl")||"oahu").toLowerCase();
const sb={rpc:async()=>({data:[{
  slug:"townad-demo-"+_ISL, name:"Your Beach Grill", segment:"town_ad",
  island:_ISL, region:_REGION[_ISL]||"Waikīkī", primary_hex:"0f4c5c",
  monthly_cents:3000, live:true, paid_at:new Date().toISOString()
}],error:null})};''',
    "the supabase client init")

# 2. token — d.html bails on an empty one; the stubbed rpc ignores the value
s = sub_once(s,
    'const token=(m?m[1]:new URLSearchParams(location.search).get("t")||"");',
    'const token=(m?m[1]:new URLSearchParams(location.search).get("t")||"sample");  // DEMO',
    "the token parse")

# 3. QR target.
#    A real partner's QR opens their co-brand page: live = SITE + "/p/" + slug (NO query), and
#    qrUrl() then appends "?ref=...". The sample has no partner row, so point it at the live
#    guide instead — but it MUST stay query-free or qrUrl() produces a second "?" and the ref
#    param arrives mangled ("slug?ref=slug"), which _activeRefSlug() sanitises into a slug that
#    doesn't exist. That silently killed the demo QR once. /go/<island> is query-free and
#    resolveIsland() reads the island straight off the path.
s = sub_once(s,
    '  const live=SITE+"/p/"+p.slug;',
    '  const live=SITE+"/go/"+_ISL;   // DEMO: query-free base — see build-townad-demo.py',
    "the live URL")

# 4. honest banner
s = sub_once(s, '<body>', '''<body>
<div style="background:#F0B429;color:#0c333d;font:600 13.5px/1.45 -apple-system,BlinkMacSystemFont,'Segoe UI',system-ui,sans-serif;padding:9px 14px;text-align:center">
  Sample dashboard — “Your Beach Grill” is made up. This is the real dashboard a Town&nbsp;Ad partner
  gets after paying; the QR codes below scan to the live guide. Uploading here won’t publish.
</div>''', "the body tag")

OUT.write_text(s, encoding="utf-8")
print(f"  wrote {OUT.name} ({len(s):,} bytes) from {SRC.name}")
